---
title: "In Class"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library('tidyverse')
library('tidytext')
```


I want to compare usage of certain words in Fox News vs MSNBC tweets. How can we go about that using what we learned in the previous class?
```{r, message=FALSE}
raw_dat = read_csv('tweet_data.csv') 

dat = raw_dat %>% 
  filter(screen_name %in% c('MSNBC', 'FoxNews')) %>%
  select(screen_name, full_text)

head(dat)
```

```{r}
# Unnest words into tokens and count them => n
tweet_words <- dat %>%
  unnest_tokens(word, full_text) %>%
  count(screen_name, word, sort=TRUE)
```

```{r}
# Get the total number of words for each screen name
total_words <- tweet_words %>%
  group_by(screen_name) %>%
  summarize(total = sum(n))
```

```{r}
# Now join by screen_name (1st column is default) 
tweet_words <- left_join(tweet_words, total_words)

```

```{r}
# Now we can plot how often a word is used by each screen name by how many words they use...to measure importance?
tweet_words %>%
  ggplot(aes(n/total, fill=screen_name)) +
  geom_histogram(show.legend = FALSE) +
  #xlim(NA, 0.0009) + # what's this?
  facet_wrap(~screen_name, ncol = 2, scales = "free_y")

```

```{r}
# Now we need to apply Zipf's law:
# The frequency that a word appears is inversely proportional to its rank
# We have a handy function for that bind_tf_idf!
tweet_words <- tweet_words %>%
  bind_tf_idf(word, screen_name, n) %>% # resverse rank by the numbrer of times a word is used!
  select(-total) %>% # not needed for Zipf plot we'll be doing next
  arrange(desc(tf_idf) )
```

```{r, message=FALSE}
# Now lets plot based on word ranking
tweet_words %>%
  arrange(desc(tf_idf)) %>%
  mutate(word = factor(word, levels = rev(unique(word)))) %>%
  group_by(screen_name) %>%
  top_n(25) %>%
  ungroup() %>%
  ggplot(aes(word, tf_idf, fill=screen_name)) +
  geom_col(show.legend = FALSE) +
  labs(x = NULL, y = 'tf-idf') + #what's this???
  facet_wrap(~screen_name, ncol = 2, scales = 'free') +
  coord_flip()
```

